services:
  blinko-website:
    container_name: blinko-website
    image: jsongo/blinko:latest
    build:
      context: .
      args:
        USE_MIRROR: "true"
      dockerfile: ./dockerfile
      # 增加构建时共享内存
      shm_size: '2gb'
    # 运行时资源限制
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:1111}
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL:-http://localhost:1111}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    restart: always
    volumes:
      - ./data:/app/.blinko
    ports:
      - ${BLINKO_PORT:-1111}:1111
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:1111/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s