# docker-compose.yml
version: '3'

networks:
  blinko-network:
    driver: bridge

services:
  blinko-website:
    container_name: blinko-website
    image: blinkospace/blinko:latest
    build:
      context: .
      args:
        USE_MIRROR: "true"
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:1111}
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL:-http://localhost:1111}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    restart: always
    volumes:
      - ./data:/app/.blinko
    ports:
      - ${BLINKO_PORT:-27539}:1111
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://blinko-website:1111/" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - blinko-network
